<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuFj2eb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuFj2eb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXuFj2eb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXuFj2eb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXuFj2eb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XuFj2eb',
    'container.build_id' => '6fb0fdd0',
    'container.build_time' => 1645394392,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuFj2eb');
