<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container41FGVSl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container41FGVSl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container41FGVSl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container41FGVSl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container41FGVSl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '41FGVSl',
    'container.build_id' => '1691fd30',
    'container.build_time' => 1645494129,
], __DIR__.\DIRECTORY_SEPARATOR.'Container41FGVSl');
